version: '3'

services:
  nginx:
    image: nginx:1.16-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - nginx:/var/www
      - certbot-etc:/etc/letsencrypt
    networks:
      - bingo_app-network
      - crossridgehoa_app-network
      - blog_app-network
      - blazorchat_app-network

  certbot-hoa:
    depends_on:
      - nginx
    image: certbot/certbot
    container_name: certbot-hoa
    volumes:
      - certbot-etc:/etc/letsencrypt
      - nginx:/var/www 
    command: certonly --webroot --webroot-path=/var/www/crossridgehoa.org/html --email crossridgehoa@gmail.com --agree-tos --no-eff-email --force-renewal -d crossridgehoa.org -d www.crossridgehoa.org

  certbot-scottdcarpenter:
    depends_on:
      - nginx
    image: certbot/certbot
    container_name: certbot-scottdcarpenter
    volumes:
      - certbot-etc:/etc/letsencrypt
      - nginx:/var/www 
    command: certonly --webroot --webroot-path=/var/www/scottdcarpenter.com/html --email sdcarpenter@gmail.com --agree-tos --no-eff-email --force-renewal -d scottdcarpenter.com -d www.scottdcarpenter.com -d bingo.scottdcarpenter.com -d blog.scottdcarpenter.com -d blazorchat.scottdcarpenter.com

volumes:
  certbot-etc:
  nginx:

networks:
  bingo_app-network:
    external: true
  crossridgehoa_app-network:
    external: true
  blog_app-network:
    external: true
  blazorchat_app-network:
    external: true
